when@dev:
    debug:
        # Enables the dump() function for development environment
        dump_destination: "php://stderr"
        
when@test:
    debug:
        dump_destination: "php://stderr"
