services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      # Remote PostgreSQL (Render) with sslmode=require
      - DATABASE_URL=postgresql://boutique_francaise_6okf_user:wxCWqnVtHvxTR8ful0z5rRKDiFFLPPdz@dpg-d3t7507gi27c73cn0ep0-a.oregon-postgres.render.com/boutique_francaise_6okf?sslmode=require
    depends_on:
      - mailer
    volumes:
      - ./:/app
      - ./public/uploads:/app/public/uploads
    networks:
      - boutique-network

  mailer:
    image: axllent/mailpit
    ports:
      - "8026:8025" # web UI (host:container)
      - "1026:1025" # smtp  (host:container)
    networks:
      - boutique-network

volumes:
  mysql_data:

networks:
  boutique-network:
    driver: bridge