<?php

namespace Container3cMItyV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixUserRolesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\FixUserRolesCommand' shared autowired service.
     *
     * @return \App\Command\FixUserRolesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'FixUserRolesCommand.php';

        $container->privates['App\\Command\\FixUserRolesCommand'] = $instance = new \App\Command\FixUserRolesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('app:fix-user-roles');
        $instance->setDescription('Corrige les rôles des utilisateurs dans la base de données');

        return $instance;
    }
}
