<?php

namespace Container3cMItyV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecuritySubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\SecuritySubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\SecuritySubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'SecuritySubscriber.php';

        return $container->privates['App\\EventSubscriber\\SecuritySubscriber'] = new \App\EventSubscriber\SecuritySubscriber(($container->services['router'] ?? $container->getRouterService()));
    }
}
