home:
    path: /
    controller: App\Controller\HomeController::index

controllers:
    resource: ../src/Controller/
    type: attribute
admin_controllers:
    resource: ../src/Controller/Admin/
    type: attribute
