<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPGxIxZl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPGxIxZl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPGxIxZl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPGxIxZl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPGxIxZl\App_KernelDevDebugContainer([
    'container.build_hash' => 'PGxIxZl',
    'container.build_id' => 'a8a421b4',
    'container.build_time' => 1760965340,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPGxIxZl');
